"""
CLI for qmri-neuropipe with robust config/CLI argument merging.

This module provides:
- Config file loading (JSON/YAML)
- Command line argument parsing
- Intelligent merging (CLI overrides config)
- Required argument validation
- Clear error messages
"""

from __future__ import annotations
import os
import json
import warnings
from pathlib import Path
from typing import List, Optional
import typer
from rich.table import Table

# Global Warning Silencing
# 1. Suppress resource_tracker warnings (benign semaphore "leaks" at shutdown in some envs)
warnings.filterwarnings("ignore", category=UserWarning, module="multiprocessing.resource_tracker")
warnings.filterwarnings("ignore", message=".*resource_tracker: There appear to be.*", category=UserWarning)
warnings.filterwarnings("ignore", message=".*resource_tracker: '/loky-.*", category=UserWarning)

# 2. Suppress solution inaccuracy warnings (e.g. from CVXPY used in MAPMRI)
warnings.filterwarnings("ignore", message=".*Solution may be inaccurate.*", category=UserWarning)
# 3. Suppress DIPY DKI overflow warnings
warnings.filterwarnings("ignore", message=".*overflow encountered in exp.*", category=RuntimeWarning)
warnings.filterwarnings("ignore", message=".*invalid value encountered in log.*", category=RuntimeWarning)


from qmri_neuropipe.core import BasePipeline, PipelineConfig
from qmri_neuropipe.core.exceptions import ConfigurationError
from qmri_neuropipe.core.parallel import run_parallel as run_parallel_tasks
from qmri_neuropipe.core.ui import console
from qmri_neuropipe.io import DataLoader
from qmri_neuropipe.workflows.pipelines.import_workflow import ImportWorkflow


app = typer.Typer(add_completion=False, help="qmri-neuropipe: Robust BIDS MRI processing pipeline")
container_app = typer.Typer(help="Run qmri-neuropipe through an Apptainer/Singularity container.")
app.add_typer(container_app, name="container")


def _counts_table(title: str, counts: dict[str, int]) -> Table:
    table = Table(title=title)
    table.add_column("Type", style="bold")
    table.add_column("Count", justify="right", style="cyan")
    for name, count in counts.items():
        table.add_row(name, str(count))
    return table


def _print_inventory(inventory, *, details: bool = False) -> None:
    overview = Table(title=inventory.name or "BIDS Dataset")
    overview.add_column("Property", style="bold")
    overview.add_column("Value", style="cyan")
    overview.add_row("Path", inventory.path)
    if inventory.rawdata_path != inventory.path:
        overview.add_row("Raw data", inventory.rawdata_path)
    overview.add_row("BIDS version", inventory.bids_version or "Unknown")
    overview.add_row("Participants", str(inventory.n_subjects))
    overview.add_row("Distinct session labels", str(inventory.n_sessions))
    overview.add_row("Participant/session observations", str(inventory.n_observations))
    overview.add_row("Sessionless participants", str(len(inventory.sessionless_subjects)))
    overview.add_row("Primary data files", str(inventory.raw_data.n_files))
    console.print(overview)

    if inventory.raw_data.modality_coverage:
        coverage = Table(title="Modality coverage")
        coverage.add_column("Modality", style="bold")
        coverage.add_column("Subjects", justify="right")
        coverage.add_column("Observations", justify="right")
        coverage.add_column("Files", justify="right", style="cyan")
        coverage.add_column("Data types")
        for modality, counts in inventory.raw_data.modality_coverage.items():
            coverage.add_row(
                modality,
                str(counts.n_subjects),
                str(counts.n_observations),
                str(counts.n_files),
                ", ".join(counts.suffixes),
            )
        console.print(coverage)
    if inventory.raw_data.suffixes:
        console.print(_counts_table("Raw data by suffix", inventory.raw_data.suffixes))

    if inventory.derivatives:
        table = Table(title="Derivative datasets")
        table.add_column("Dataset", style="bold")
        table.add_column("Generated by")
        table.add_column("Participants", justify="right")
        table.add_column("Observations", justify="right")
        for derivative in inventory.derivatives:
            producers = ", ".join(
                " ".join(str(item) for item in (producer.get("Name"), producer.get("Version")) if item)
                for producer in derivative.generated_by
            ) or "Unknown"
            table.add_row(
                derivative.name,
                producers,
                str(derivative.n_subjects),
                str(derivative.n_observations),
            )
        console.print(table)

        coverage = Table(title="Derivative model coverage")
        coverage.add_column("Derivative", style="bold")
        coverage.add_column("Modality")
        coverage.add_column("Subjects", justify="right")
        coverage.add_column("Observations", justify="right")
        coverage.add_column("Models", style="cyan")
        for derivative in inventory.derivatives:
            for modality, counts in derivative.products.items():
                coverage.add_row(
                    derivative.name,
                    modality,
                    str(counts.n_subjects),
                    str(counts.n_observations),
                    ", ".join(counts.models) or "—",
                )
        if coverage.row_count:
            console.print(coverage)

        downstream = Table(title="Downstream derivative coverage")
        downstream.add_column("Derivative", style="bold")
        downstream.add_column("Modality")
        downstream.add_column("ROI stats", justify="right")
        downstream.add_column("Normalized", justify="right")
        downstream.add_column("Template spaces", style="cyan")
        for derivative in inventory.derivatives:
            for modality, counts in derivative.products.items():
                denominator = counts.n_observations
                downstream.add_row(
                    derivative.name,
                    modality,
                    f"{counts.roi_stats_observations}/{denominator}" if denominator else "—",
                    f"{counts.normalized_observations}/{denominator}" if denominator else "—",
                    ", ".join(counts.template_spaces) or "—",
                )
        if downstream.row_count:
            console.print(downstream)

        if details:
            model_details = Table(title="Detailed model coverage")
            model_details.add_column("Derivative", style="bold")
            model_details.add_column("Modality")
            model_details.add_column("Model", style="cyan")
            model_details.add_column("Subjects", justify="right")
            model_details.add_column("Observations", justify="right")
            for derivative in inventory.derivatives:
                for modality, products in derivative.products.items():
                    for model, counts in products.model_coverage.items():
                        model_details.add_row(
                            derivative.name,
                            modality,
                            model,
                            str(counts.n_subjects),
                            str(counts.n_observations),
                        )
            if model_details.row_count:
                console.print(model_details)

    if inventory.processing_gaps:
        gaps = Table(title="Processing gaps")
        gaps.add_column("Modality", style="bold")
        gaps.add_column("Raw observations", justify="right")
        gaps.add_column("Processed", justify="right")
        gaps.add_column("Missing", justify="right", style="yellow")
        gaps.add_column("Coverage", justify="right", style="cyan")
        for modality, counts in inventory.processing_gaps.items():
            coverage_pct = (
                100.0 * counts.processed_observations / counts.raw_observations
                if counts.raw_observations
                else 0.0
            )
            gaps.add_row(
                modality,
                str(counts.raw_observations),
                str(counts.processed_observations),
                str(counts.missing_observations),
                f"{coverage_pct:.1f}%",
            )
        console.print(gaps)

        if details:
            missing = Table(title="Missing derivative observations")
            missing.add_column("Modality", style="bold")
            missing.add_column("Subject/session observations", style="yellow")
            for modality, counts in inventory.processing_gaps.items():
                if counts.missing:
                    missing.add_row(modality, ", ".join(counts.missing))
            if missing.row_count:
                console.print(missing)

    if inventory.session_breakdown:
        raw_sessions = Table(title="Raw coverage by session")
        raw_sessions.add_column("Session", style="bold")
        raw_sessions.add_column("Modality")
        raw_sessions.add_column("Subjects", justify="right")
        raw_sessions.add_column("Observations", justify="right")
        raw_sessions.add_column("Data types", style="cyan")
        for session, summary in inventory.session_breakdown.items():
            for modality, counts in summary.raw_modalities.items():
                raw_sessions.add_row(
                    session,
                    modality,
                    str(counts.n_subjects),
                    str(counts.n_observations),
                    ", ".join(counts.suffixes),
                )
        if raw_sessions.row_count:
            console.print(raw_sessions)

        derivative_sessions = Table(title="Derivative model coverage by session")
        derivative_sessions.add_column("Session", style="bold")
        derivative_sessions.add_column("Derivative")
        derivative_sessions.add_column("Modality")
        derivative_sessions.add_column("Subjects", justify="right")
        derivative_sessions.add_column("Observations", justify="right")
        derivative_sessions.add_column("Models", style="cyan")
        for session, summary in inventory.session_breakdown.items():
            for derivative, products in summary.derivative_products.items():
                for modality, counts in products.items():
                    derivative_sessions.add_row(
                        session,
                        derivative,
                        modality,
                        str(counts.n_subjects),
                        str(counts.n_observations),
                        ", ".join(counts.models) or "—",
                    )
        if derivative_sessions.row_count:
            console.print(derivative_sessions)

        session_gaps = Table(title="Processing gaps by session")
        session_gaps.add_column("Session", style="bold")
        session_gaps.add_column("Modality")
        session_gaps.add_column("Raw", justify="right")
        session_gaps.add_column("Processed", justify="right")
        session_gaps.add_column("Missing", justify="right", style="yellow")
        session_gaps.add_column("Coverage", justify="right", style="cyan")
        for session, summary in inventory.session_breakdown.items():
            for modality, counts in summary.processing_gaps.items():
                coverage_pct = (
                    100.0 * counts.processed_observations / counts.raw_observations
                    if counts.raw_observations
                    else 0.0
                )
                session_gaps.add_row(
                    session,
                    modality,
                    str(counts.raw_observations),
                    str(counts.processed_observations),
                    str(counts.missing_observations),
                    f"{coverage_pct:.1f}%",
                )
        if session_gaps.row_count:
            console.print(session_gaps)

    for warning in inventory.warnings:
        console.print(f"[yellow]Warning:[/yellow] {warning}")


@app.command("inspect")
def inspect_command(
    bids_dir: Path = typer.Argument(..., help="BIDS dataset directory.", exists=True, file_okay=False),
    rawdata_dir: Optional[Path] = typer.Option(
        None,
        "--rawdata-dir",
        help="Raw BIDS data directory, absolute or relative to BIDS_DIR (for example: rawdata).",
    ),
    derivatives: bool = typer.Option(False, "--derivatives", help="Include datasets beneath derivatives/."),
    processing_gaps: bool = typer.Option(
        False,
        "--processing-gaps",
        help="Compare raw observations with available derivative products.",
    ),
    by_session: bool = typer.Option(
        False,
        "--by-session",
        help="Break raw and derivative coverage counts out by session label.",
    ),
    details: bool = typer.Option(False, "--details", help="Show per-model derivative coverage."),
    participant_label: Optional[List[str]] = typer.Option(None, "--participant-label", "-p", help="Participant label to include; repeat for multiple labels."),
    session_label: Optional[List[str]] = typer.Option(None, "--session-label", "-s", help="Session label to include; repeat for multiple labels."),
    output_format: str = typer.Option("text", "--format", help="Output format: text or json."),
    output: Optional[Path] = typer.Option(None, "--output", "-o", help="Write the report to a file."),
):
    """Inspect raw BIDS contents and available derivative datasets."""
    from qmri_neuropipe.io.bids_inventory import inspect_bids_dataset

    normalized_format = output_format.lower()
    if normalized_format not in {"text", "json"}:
        console.print("[bold red]Error:[/bold red] --format must be either text or json.")
        raise typer.Exit(code=2)
    if output and normalized_format != "json":
        console.print("[bold red]Error:[/bold red] --output currently requires --format json.")
        raise typer.Exit(code=2)

    try:
        inventory = inspect_bids_dataset(
            bids_dir,
            rawdata_dir=rawdata_dir,
            participants=participant_label,
            sessions=session_label,
            include_derivatives=derivatives or details or processing_gaps,
            include_processing_gaps=processing_gaps,
            include_session_breakdown=by_session,
        )
    except Exception as exc:
        console.print(f"[bold red]Inspection failed:[/bold red] {exc}")
        raise typer.Exit(code=1)

    if normalized_format == "json":
        rendered = json.dumps(inventory.to_dict(), indent=2, sort_keys=True)
        if output:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(rendered + "\n", encoding="utf-8")
            console.print(f"[green]Inventory written to:[/green] {output}")
        else:
            # Avoid Rich's terminal-width wrapping, which would corrupt JSON
            # string values when stdout is consumed programmatically.
            typer.echo(rendered)
    else:
        _print_inventory(inventory, details=details)


@container_app.command(
    "run",
    add_help_option=False,
    context_settings={"allow_extra_args": True, "ignore_unknown_options": True},
)
def container_run(ctx: typer.Context):
    """Run using the existing container runner; use --help for its options."""
    from qmri_neuropipe.container_runner import main as container_main

    exit_code = container_main(list(ctx.args))
    if exit_code:
        raise typer.Exit(code=exit_code)




def _print_args(config: PipelineConfig, **extra_kwargs):
    """
    Display pipeline arguments in a formatted table.
    
    Args:
        config: Pipeline configuration object
        **extra_kwargs: Additional arguments to display
    """
    table = Table(title="qmri-neuropipe Configuration")
    table.add_column("Parameter", style="bold")
    table.add_column("Value", style="cyan")
    
    # Core paths
    table.add_row("bids_dir", str(config.bids_dir) if config.bids_dir else "Not set")
    table.add_row("output_dir", str(config.output_dir) if config.output_dir else "Not set")
    table.add_row("work_dir", str(config.work_dir) if config.work_dir else "Not set")
    
    # Subject/session selection
    if config.participant_label:
        table.add_row("participant_label", str(config.participant_label))
    if config.session_label:
        table.add_row("session_label", str(config.session_label))
    
    # Computational resources
    table.add_row("n_cpus", str(config.n_cpus))
    table.add_row("memory_gb", str(config.memory_gb))
    table.add_row("use_gpu", str(config.use_gpu))
    
    # Execution control
    table.add_row("skip_existing", str(config.skip_existing))
    table.add_row("stop_on_error", str(config.stop_on_error))
    
    # Logging
    table.add_row("log_level", config.log_level)
    table.add_row("verbose", str(config.verbose))
    table.add_row("debug", str(config.debug))
    
    # Extra arguments
    for k, v in extra_kwargs.items():
        table.add_row(k, str(v))
    
    console.print(table)


def merge_cli_and_config(
    config_file: Optional[Path],
    cli_args: dict
) -> PipelineConfig:
    """
    Merge configuration from file and CLI arguments.
    
    Priority (highest to lowest):
    1. CLI arguments (explicitly provided by user)
    2. Config file values
    3. Default values
    
    Args:
        config_file: Path to config file (if provided)
        cli_args: Dictionary of CLI arguments (only non-None values)
    
    Returns:
        Merged PipelineConfig object
    
    Raises:
        ConfigurationError: If config file is invalid or required fields missing
    """
    normalized_cli_args = {}
    for key, value in cli_args.items():
        if value is None:
            continue
        if key in ['participant_label', 'session_label'] and isinstance(value, str):
            value = [value]
        normalized_cli_args[key] = value

    # Start with config file if provided
    if config_file:
        try:
            console.print(f"[blue]Loading configuration from:[/blue] {config_file}")
            config = PipelineConfig.from_file(config_file, overrides=normalized_cli_args)
        except FileNotFoundError:
            raise ConfigurationError(
                f"Configuration file not found: {config_file}",
                details="Please check the path and try again."
            )
        except Exception as e:
            raise ConfigurationError(
                f"Failed to load configuration file: {config_file}",
                details=str(e)
            )
    else:
        # Start with empty config
        config = PipelineConfig()
    
    # Override with CLI arguments (only if explicitly provided)
    # We only merge non-None values to distinguish between "not provided" and "provided as None"
    for key, value in normalized_cli_args.items():
        if value is not None:
            config.set(key, value)
    
    return config


def validate_required_arguments(config: PipelineConfig) -> None:
    """
    Validate that all required arguments are provided.
    
    Args:
        config: Pipeline configuration to validate
    
    Raises:
        ConfigurationError: If required arguments are missing
    """
    import_dicom_dir = config.get("import.dicom_dir")
    auto_import = bool(import_dicom_dir) and bool(config.get("import.auto_run", True))

    required_fields = {
        'bids_dir': 'Input BIDS dataset directory',
        'output_dir': 'Output directory for derivatives',
    }
    
    missing = []
    for field, description in required_fields.items():
        value = getattr(config, field, None)
        if value is None:
            missing.append(f"  --{field.replace('_', '-')} : {description}")
    
    if missing:
        error_msg = (
            "Missing required arguments. Please provide them via config file or command line:\n\n"
            + "\n".join(missing) +
            "\n\nExamples:\n"
            "  1. Via command line:\n"
            "     qmri-neuropipe --bids-dir /data/bids --output-dir /data/derivatives\n\n"
            "  2. Via config file:\n"
            "     qmri-neuropipe --config config.yaml\n\n"
            "  3. Mixed (CLI overrides config):\n"
            "     qmri-neuropipe --config config.yaml --n-cpus 16"
        )
        raise ConfigurationError(error_msg)
    
    # Validate paths exist
    if not config.bids_dir.exists() and not auto_import:
        raise ConfigurationError(
            f"BIDS directory does not exist: {config.bids_dir}",
            details="Please check the path and ensure it's accessible."
        )
    
    if config.bids_dir.exists() and not config.bids_dir.is_dir():
        raise ConfigurationError(
            f"BIDS directory path is not a directory: {config.bids_dir}"
        )


def _normalize_optional_bids_label(value: Optional[str], prefix: str) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    if text.lower() in {"none", "null", "n/a", "na"}:
        return None
    return text.removeprefix(prefix)


def _parse_csv_int_option(value: Optional[str], option_name: str) -> Optional[list[int]]:
    if value is None:
        return None
    parts = [part.strip() for part in str(value).split(",") if part.strip()]
    try:
        parsed = sorted({int(part) for part in parts})
    except ValueError:
        console.print(
            f"[bold red]Error:[/bold red] Invalid {option_name} format: {value}. Expected comma-separated integers."
        )
        raise typer.Exit(code=1)
    if any(idx < 0 for idx in parsed):
        console.print(
            f"[bold red]Error:[/bold red] Invalid {option_name} format: {value}. Indices must be non-negative."
        )
        raise typer.Exit(code=1)
    return parsed


def _resolve_auto_import_subject_session(config: PipelineConfig) -> tuple[Optional[str], Optional[str]]:
    import_subject = config.get("import.subject")
    import_session = config.get("import.session")

    if import_subject:
        import_subject = _normalize_optional_bids_label(import_subject, "sub-")
    elif config.participant_label:
        if len(config.participant_label) != 1:
            raise ConfigurationError(
                "Automatic import requires exactly one subject. Set `import.subject` explicitly or provide a single participant_label."
            )
        import_subject = _normalize_optional_bids_label(config.participant_label[0], "sub-")

    if import_session:
        import_session = _normalize_optional_bids_label(import_session, "ses-")
    elif config.session_label:
        if len(config.session_label) != 1:
            raise ConfigurationError(
                "Automatic import requires at most one session. Set `import.session` explicitly or provide a single session_label."
            )
        import_session = _normalize_optional_bids_label(config.session_label[0], "ses-")

    return import_subject, import_session


def maybe_run_auto_import(config: PipelineConfig, verbose: bool = False) -> None:
    dicom_dir = config.get("import.dicom_dir")
    auto_run = config.get("import.auto_run", True)
    if not dicom_dir or auto_run is False:
        return

    dicom_dir = Path(dicom_dir)
    if not dicom_dir.exists():
        raise ConfigurationError(f"Automatic import source not found: {dicom_dir}")

    import_method = config.get("import.method", "dcm2bids")
    subject, session = _resolve_auto_import_subject_session(config)
    if import_method == "dcm2bids" and not subject:
        raise ConfigurationError(
            "Automatic import with dcm2bids requires a subject. Set `import.subject` or provide a single participant_label."
        )

    config.bids_dir.mkdir(parents=True, exist_ok=True)
    if config.work_dir:
        config.work_dir.mkdir(parents=True, exist_ok=True)

    workflow = ImportWorkflow(config=config)
    context = {}
    if subject:
        context["subject"] = subject
    if session:
        context["session"] = session

    workflow.build_pipeline(context)
    workflow.run(dicom_dir=dicom_dir, output_dir=config.bids_dir, context=context)


@app.command("import")
def import_command(
    dicom_dir: Path = typer.Option(
        ...,
        "--dicom-dir",
        help="Path to the source DICOM directory or .tgz/.tar.gz archive to import",
        exists=True,
        file_okay=True,
        dir_okay=True,
        readable=True,
    ),
    output_dir: Path = typer.Option(
        ...,
        "--output-dir",
        help="Path to the target BIDS or NIfTI output directory",
        file_okay=False,
        dir_okay=True,
        writable=True,
    ),
    config_file: Optional[Path] = typer.Option(
        None,
        "--config",
        "-c",
        help="Path to YAML/JSON configuration file",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
    ),
    work_dir: Optional[Path] = typer.Option(
        None,
        "--work-dir",
        help="Optional working directory",
    ),
    subject: Optional[str] = typer.Option(
        None,
        "--subject",
        "-p",
        help="Subject ID for import workflows that require it, such as dcm2bids",
    ),
    session: Optional[str] = typer.Option(
        None,
        "--session",
        "-s",
        help="Optional session ID for import workflows",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        help="Print the resolved import configuration before running",
    ),
):
    """
    Import source DICOMs using the configured dcm2niix/dcm2bids workflow.
    """
    try:
        cli_args = {
            "output_dir": output_dir,
            "work_dir": work_dir,
        }
        config = merge_cli_and_config(config_file, cli_args)
        if config.bids_dir is None:
            config.bids_dir = output_dir
        if config.output_dir is None:
            config.output_dir = output_dir

        import_method = config.get("import.method", "dcm2bids")
        if import_method == "dcm2bids" and not subject:
            raise ConfigurationError("`--subject` is required when import.method is dcm2bids.")

        output_dir.mkdir(parents=True, exist_ok=True)
        if config.work_dir:
            config.work_dir.mkdir(parents=True, exist_ok=True)

        if verbose or config.verbose:
            console.print("\n[bold green]Import configuration[/bold green]\n")
            _print_args(
                config,
                dicom_dir=dicom_dir,
                import_method=import_method,
                subject=subject,
                session=session,
            )

        workflow = ImportWorkflow(config=config)
        context = {}
        if subject:
            context["subject"] = subject.removeprefix("sub-")
        if session:
            context["session"] = session.removeprefix("ses-")

        workflow.build_pipeline(context)
        workflow.run(
            dicom_dir=dicom_dir,
            output_dir=output_dir,
            context=context,
        )

        console.print(f"\n[bold green]Import complete.[/bold green] Output written to: {output_dir}")
    except ConfigurationError as e:
        console.print(f"[bold red]Configuration error:[/bold red] {e}")
        raise typer.Exit(code=2)
    except Exception as e:
        console.print(f"[bold red]Import failed:[/bold red] {e}")
        raise typer.Exit(code=1)


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    # Core paths (can be provided via CLI or config)
    dicom_dir: Optional[Path] = typer.Option(
        None,
        "--dicom-dir",
        help="Optional DICOM source directory or archive for automatic import before processing",
        exists=True,
        file_okay=True,
        dir_okay=True,
        readable=True,
    ),
    bids_dir: Optional[Path] = typer.Option(
        None, 
        "--bids-dir",
        help="Path to BIDS dataset directory",
        exists=False,  # We'll validate manually for better error messages
        file_okay=False, 
        dir_okay=True, 
        readable=True
    ),
    output_dir: Optional[Path] = typer.Option(
        None,
        "--output-dir",
        help="Path to output directory for derivatives",
        file_okay=False, 
        dir_okay=True,
        writable=True
    ),
    work_dir: Optional[Path] = typer.Option(
        None, 
        "--work-dir",
        help="Path to working directory for temporary files"
    ),
    
    # Config file
    config_file: Optional[Path] = typer.Option(
        None, 
        "--config", "-c",
        help="Path to YAML/JSON configuration file",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True
    ),
    
    # Pipeline selection
    pipeline: Optional[str] = typer.Option(
        None, 
        "--pipeline",
        help="Pipeline to run (e.g., dmri, fmri, anat)"
    ),
    level: Optional[str] = typer.Option(
        None,
        "--level",
        help="BIDS App analysis level: participant, group (default: participant)"
    ),
    
    # Subject/session selection
    participant_label: Optional[str] = typer.Option(
        None, 
        "--participant-label", "-p",
        help="Participant ID(s) to process (e.g., sub-01 or 01)"
    ),
    session_label: Optional[str] = typer.Option(
        None, 
        "--session-label", "-s",
        help="Session ID(s) to process (e.g., ses-01 or 01)"
    ),
    
    # Computational resources
    n_cpus: Optional[int] = typer.Option(
        None, 
        "--n-cpus",
        help="Number of CPUs to use"
    ),
    memory_gb: Optional[float] = typer.Option(
        None,
        "--memory-gb",
        help="Memory limit in GB"
    ),
    use_gpu: Optional[bool] = typer.Option(
        None,
        "--use-gpu/--no-gpu",
        help="Enable GPU acceleration (if available)"
    ),
    omp_nthreads: Optional[int] = typer.Option(
        None,
        "--omp-nthreads",
        help="Number of OpenMP threads"
    ),
    gpu_ids: Optional[str] = typer.Option(
        None,
        "--gpu-ids",
        help="GPU IDs to use (e.g. '0' or '0,1')"
    ),
    
    # Execution control
    skip_existing: Optional[bool] = typer.Option(
        None,
        "--skip-existing/--no-skip-existing",
        help="Skip already processed subjects"
    ),
    stop_on_error: Optional[bool] = typer.Option(
        None,
        "--stop-on-error/--continue-on-error",
        help="Stop pipeline on first error"
    ),
    rerun_from_step: Optional[str] = typer.Option(
        None,
        "--rerun-from-step",
        help="Rerun the selected pipeline from this processing step onward (e.g., normalization)",
    ),
    skip_bids_validation: bool = typer.Option(
        False, 
        "--skip-bids-validation",
        help="Skip BIDS dataset validation"
    ),
    
    # Logging
    log_level: Optional[str] = typer.Option(
        None,
        "--log-level",
        help="Logging level (DEBUG, INFO, WARNING, ERROR)"
    ),
    verbose: bool = typer.Option(
        False, 
        "--verbose", "-v",
        help="Enable verbose output"
    ),
    debug: Optional[bool] = typer.Option(
        None,
        "--debug",
        help="Enable debug mode"
    ),
    
    # Other options
    dry_run: bool = typer.Option(
        False, 
        "--dry-run",
        help="Perform a dry run without executing the pipeline"
    ),
    jobs: int = typer.Option(
        1,
        "--jobs", "-j",
        help="Number of parallel jobs (subjects) to run locally"
    ),
    outlier_indices: Optional[str] = typer.Option(
        None,
        "--outlier-indices",
        help="Comma-separated list of volume indices to remove (e.g., '0,1,2')"
    ),
    spgr_exclude: Optional[str] = typer.Option(
        None,
        "--spgr-exclude",
        help="Comma-separated list of logical SPGR acquisition indices to exclude (e.g., '0,1,3')"
    ),
    ssfp_exclude: Optional[str] = typer.Option(
        None,
        "--ssfp-exclude",
        help="Comma-separated list of logical SSFP acquisition indices to exclude (e.g., '5,10')"
    ),
    subjects_file: Optional[Path] = typer.Option(
        None,
        "--subjects-file",
        help="Path to text file containing 'subject,session' list (for HTCondor submission)",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True
    ),
    submit: bool = typer.Option(
        False,
        "--submit",
        help="Generate HTCondor submit file (saves to default location 'job.sub')"
    ),
    submit_file: Optional[Path] = typer.Option(
        None,
        "--submit-file",
        help="Generate HTCondor submit file at a specific path. Implies --submit.",
        file_okay=True,
        dir_okay=False,
        writable=True
    ),
):
    """
    qmri-neuropipe: Robust neuroimaging pipeline for BIDS datasets.
    
    This command processes MRI data using configurable pipelines. Configuration
    can be provided via a YAML/JSON file and/or command line arguments.
    Command line arguments take precedence over config file values.
    
    REQUIRED ARGUMENTS (via CLI or config file):
    
        --bids-dir: Path to BIDS dataset directory
        --output-dir: Path to output directory
    
    EXAMPLES:
    
        # Using config file only:
        qmri-neuropipe --config config.yaml
        
        # Using CLI arguments only:
        qmri-neuropipe --bids-dir /data/bids --output-dir /data/derivatives
        
        # Mixed (CLI overrides config):
        qmri-neuropipe --config config.yaml --n-cpus 16 --participant-label sub-01
        
        # Process specific subjects:
        qmri-neuropipe --config config.yaml -p sub-01 -s ses-01
        
        # Dry run to check configuration:
        qmri-neuropipe --config config.yaml --dry-run --verbose
    """
    if ctx.invoked_subcommand is not None:
        return

    # Keep a valid config available to the outer error handler even when
    # argument parsing or config-file loading fails before the merge.
    config = PipelineConfig(debug=debug)

    try:
        # Parse gpu_ids
        gpu_ids_list = None
        if gpu_ids is not None:
            try:
                gpu_ids_list = [int(x.strip()) for x in gpu_ids.split(',')]
            except ValueError:
                console.print(f"[bold red]Error:[/bold red] Invalid gpu_ids format: {gpu_ids}. Expected comma-separated integers.")
                raise typer.Exit(code=1)

        # Parse index-list options
        outlier_indices_list = _parse_csv_int_option(outlier_indices, "outlier-indices")
        spgr_exclude_list = _parse_csv_int_option(spgr_exclude, "spgr-exclude")
        ssfp_exclude_list = _parse_csv_int_option(ssfp_exclude, "ssfp-exclude")

        # Collect CLI arguments (only non-None values)
        # Note: pipeline and level are NOT part of PipelineConfig dataclass
        # They control which workflow runs, not how it runs
        cli_args = {
            'import.dicom_dir': dicom_dir,
            'import.auto_run': True if dicom_dir is not None else None,
            'bids_dir': bids_dir,
            'output_dir': output_dir,
            'work_dir': work_dir,
            'participant_label': participant_label,
            'session_label': session_label,
            'subjects_file': subjects_file,
            'n_cpus': n_cpus,
            'memory_gb': memory_gb,
            'use_gpu': use_gpu,
            'gpu_ids': gpu_ids_list,
            'omp_nthreads': omp_nthreads,
            'skip_existing': skip_existing,
            'stop_on_error': stop_on_error,
            'rerun_from_step': rerun_from_step,
            'log_level': log_level,
            'debug': debug,
            'jobs': jobs,
            'submit': submit,
            # Pass outlier indices to the nested config path
            'dmri.preprocessing.outliers.manual_indices': outlier_indices_list,
            'dmri.preprocessing.outliers.method': 'manual' if outlier_indices_list else None,
            'dmri.preprocessing.outliers.enabled': True if outlier_indices_list else None,
            'relaxometry.preprocessing.exclude_indices.spgr': spgr_exclude_list,
            'relaxometry.preprocessing.exclude_indices.ssfp': ssfp_exclude_list,
            # If submit_file is provided, pass it as 'submit' value (path string)
            # If submit is True but no file, pass True (or "DEFAULT")
            # We'll normalize this logic here
        }
        
        # Normalize 'submit' argument for config
        if submit_file:
             cli_args['submit'] = str(submit_file)
        elif submit:
             cli_args['submit'] = True
        else:
             cli_args['submit'] = None # Explicitly set to None if neither provided (will be removed below)

        # Remove None values to distinguish "not provided" from "explicitly None"
        cli_args = {k: v for k, v in cli_args.items() if v is not None}
        
        # Merge config file and CLI arguments
        config = merge_cli_and_config(config_file, cli_args)
        
        # Handle pipeline and level (can come from config file or CLI).
        # Priority: CLI > Config File > Defaults.
        pipeline_name = pipeline
        analysis_level = level

        if pipeline_name is None:
            pipeline_name = config.get("pipeline")
        
        if analysis_level is None:
            analysis_level = config.get("level")
        

        # Set defaults if still not specified
        if pipeline_name is None:
            # Smart default: If relaxometry explicitly configured and dmri not, use relaxometry
            if config.get("relaxometry") and not config.get("dmri"):
                pipeline_name = 'relaxometry'
            else:
                pipeline_name = 'dmri'

        if analysis_level is None:
            analysis_level = 'participant'
        
        # Validate required arguments
        validate_required_arguments(config)
        
        # Create output directories
        config.output_dir.mkdir(parents=True, exist_ok=True)
        # derivatives/qmri-neuropipe no longer created automatically
        # Outputs go directly to config.output_dir
        
        # Set work_dir if not specified
        if config.work_dir is None:
            config.work_dir = config.output_dir / "work"
        config.work_dir.mkdir(parents=True, exist_ok=True)

        maybe_run_auto_import(config, verbose=verbose)
        
        
        # --- Configure Environment for Threading (ANTs, OpenMP, etc.) ---
        # This MUST be done before importing pipeline modules that might initialize libraries (like ANTs)
        # Determine effective CPU count
        effective_cpus = config.n_cpus
        if not effective_cpus:
            # Fallback or default
            effective_cpus = 1
            
        str_cpus = str(effective_cpus)
        
        # ANTs / ITK
        os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = str_cpus
        
        # OpenMP (used by many C modules)
        # If omp_nthreads is explicitly set via CLI, use it. Otherwise default to n_cpus or system default.
        if omp_nthreads:
            os.environ["OMP_NUM_THREADS"] = str(omp_nthreads)
        else:
            # It is often safer to set OMP_NUM_THREADS to n_cpus to avoid oversubscription 
            # if the underlying libraries default to all cores.
            os.environ["OMP_NUM_THREADS"] = str_cpus
            
        # MKL / BLAS
        os.environ["MKL_NUM_THREADS"] = str_cpus
        os.environ["OPENBLAS_NUM_THREADS"] = str_cpus
        os.environ["VECLIB_MAXIMUM_THREADS"] = str_cpus
        os.environ["NUMEXPR_NUM_THREADS"] = str_cpus
        
        if config.verbose or verbose:
             console.print(f"[blue]Setting threading environment variables:[/blue] ITK={str_cpus}, OMP={os.environ['OMP_NUM_THREADS']}")

        # Print configuration if verbose
        if config.verbose or verbose or dry_run:
            extra_args = {
                "pipeline": pipeline_name,
                "level": analysis_level,
                "dry_run": dry_run,
                "skip_bids_validation": skip_bids_validation,
                "omp_nthreads": omp_nthreads,
            }
            auto_import_dicom_dir = config.get("import.dicom_dir")
            auto_import_enabled = bool(auto_import_dicom_dir) and bool(config.get("import.auto_run", True))
            if auto_import_enabled:
                import_subject, import_session = _resolve_auto_import_subject_session(config)
                extra_args.update({
                    "auto_import": True,
                    "dicom_dir": auto_import_dicom_dir,
                    "import_method": config.get("import.method", "dcm2bids"),
                    "import_subject": import_subject,
                    "import_session": import_session,
                })
            console.print("\n[bold green]Configuration validated successfully![/bold green]\n")
            _print_args(config, **extra_args)
        
        # Dry run - just validate and print config
        if dry_run:
            console.print("\n[bold yellow]Dry run complete. No processing performed.[/bold yellow]")
            return
        
        # Load data
        console.print(f"\n[blue]Loading BIDS dataset from:[/blue] {config.bids_dir}")
        loader = DataLoader(config.bids_dir)
        
        # Determine subjects/sessions to process
        if config.participant_label:
            console.print(f"Using participant label(s): {config.participant_label}")
            data = loader.load_multiple_subjects(subjects=config.participant_label, sessions=config.session_label)
        elif config.subjects_file:
            console.print(f"Using subjects from file: {config.subjects_file}")
            data = loader.load_from_subjects_file(config.subjects_file)
        else:
            console.print("No subject selection provided. Discovering all subjects...")
            data = loader.load_multiple_subjects()
        
        tasks = [t for t in data.keys() if t[0] and str(t[0]).lower() != "none"]
        if len(tasks) < len(data):
             console.print(f"[yellow]Skipped {len(data) - len(tasks)} invalid tasks with no valid subject ID.[/yellow]")
        console.print(f"Total tasks to process: {len(tasks)}")

        if not tasks and (config.participant_label or config.session_label):
            requested_parts = []
            if config.participant_label:
                requested_parts.append(f"participant_label={config.participant_label}")
            if config.session_label:
                requested_parts.append(f"session_label={config.session_label}")

            import_dicom_dir = config.get("import.dicom_dir")
            import_note = ""
            if bool(config.get("import.auto_run", True)) and not import_dicom_dir:
                import_note = (
                    " Auto-import is enabled in the config, but `import.dicom_dir` is not set, "
                    "so no DICOM import was run before subject discovery."
                )

            raise ConfigurationError(
                "No matching subject/session pairs were found in the BIDS dataset.",
                details=(
                    f"Requested {', '.join(requested_parts)} under {config.bids_dir}."
                    f"{import_note}"
                ),
            )

        if jobs > 1 and not submit:
            console.print(
                f"\n[bold blue]Running locally in PARALLEL mode with {jobs} workers.[/bold blue]"
            )

        console.print(f"\n[blue]Initializing {pipeline_name} pipeline...[/blue]")
        if pipeline_name == "dmri":
            from .workflows.pipelines.dmri import DMRIPipeline

            pipeline_obj = DMRIPipeline(config)
        elif pipeline_name == "anat":
            from .workflows.pipelines.anat import AnatPipeline

            pipeline_obj = AnatPipeline(config)
        elif pipeline_name == "relaxometry":
            from .workflows.pipelines.relaxometry import RelaxometryPipeline

            pipeline_obj = RelaxometryPipeline(config)
        elif pipeline_name == "gratio":
            from .workflows.pipelines.gratio import AggregateGRatioPipeline

            pipeline_obj = AggregateGRatioPipeline(config)
        elif pipeline_name == "fmri":
            from .workflows.pipelines.fmri_workflow import FmriWorkflow

            pipeline_obj = FmriWorkflow(config)
        else:
            raise ConfigurationError(
                f"Unsupported pipeline: {pipeline_name}",
                details="Available pipelines: dmri, anat, relaxometry, gratio, fmri",
            )

        console.print("\n[bold green]Starting pipeline execution...[/bold green]\n")
        if jobs > 1 and not submit and not isinstance(pipeline_obj, BasePipeline):
            stats = run_parallel_tasks(
                pipeline_obj.__class__,
                config,
                tasks,
                jobs,
                logger=pipeline_obj.logger,
            )
        else:
            stats = pipeline_obj.run(pairs=tasks)
        failures = stats.get("failures", [])

        if stats:
            if stats.get('n_failed', 0) > 0:
                 console.print(f"\n[bold red]Pipeline completed with errors![/bold red]")
                 
                 # Print detailed summary of failed subjects
                 if failures:
                      console.print("\n[bold red]Failed Subjects Summary:[/bold red]")
                      for f in failures:
                           sub_info = f"sub-{f.get('subject')}"
                           if f.get('session'): sub_info += f" ses-{f.get('session')}"
                           err = f.get('error', 'Unknown error')
                           console.print(f"  ❌ [bold]{sub_info}[/bold]: {err}")
                 
                 console.print(f"\n[bold yellow]Totals:[/bold yellow] Success: {stats['n_success']}, Failed: {stats['n_failed']}, Skipped: {stats['n_skipped']}")
                 raise typer.Exit(code=1)
            
            console.print("\n[bold green]Pipeline completed successfully![/bold green]")
            console.print(f"Success: {stats['n_success']}, Failed: {stats['n_failed']}, Skipped: {stats['n_skipped']}\n")
        
    except ConfigurationError as e:
        console.print(f"\n[bold red]Configuration Error:[/bold red] {e.message}")
        if e.details:
            console.print(f"[red]Details:[/red] {e.details}")
        console.print("\n[yellow]Use --help for usage information.[/yellow]\n")
        raise typer.Exit(code=1)
    
    except Exception as e:
        console.print(f"\n[bold red]Error:[/bold red] {str(e)}")
        if config.debug:
            console.print_exception()
        raise typer.Exit(code=1)


# Preserve the historical no-subcommand invocation while also providing the
# explicit command advertised by the suite-style CLI.
app.command("run")(main)


if __name__ == "__main__":
    app()
