
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qmri-neuropipe"
version = "0.0.1"
dependencies = [
    "typer>=0.12",
    "rich>=13.7",
    "pandas>=1.5",
    "pyyaml>=6.0", 
    "jinja2>=3.1", 
    "matplotlib>=3.8", 
    "antspyx>=0.3", 
    "dmipy>=1.0",
    "nibabel>=5.0",
    "numpy>=1.24,<2.0",
    "numba",
    "scipy>=1.10",
    "dipy>=1.8",
    "pywavelets",
    "threadpoolctl",
    "tqdm",
    "HD-BET",
    "dcm2bids"
]

[project.optional-dependencies]
amico = [
    "dmri-amico"
]
nexi = [
    "nexi"
]
nifreeze = [
    "nifreeze"
]
pyafq = [
    "pyAFQ"
]
mriqc = [
    "mriqc>=24.0.0; python_version<'3.12'"
]
tracker = [
    "openpyxl",
    "plotly",
    "streamlit"
]
reporting = [
    "weasyprint"
]
viewer = [
    "dash",
    "plotly",
    "pywebview"
]
all = [
    "dmri-amico",
    "nexi",
    "nifreeze",
    "openpyxl",
    "plotly",
    "pyAFQ",
    "streamlit",
    "weasyprint",
    "mriqc>=24.0.0; python_version<'3.12'",
    "dash",
    "pywebview"
]
[project.scripts]
qmri-neuropipe = "qmri_neuropipe.cli:app"
qmri-tools = "qmri_neuropipe.tools:app"

[tool.setuptools.package-data]
"qmri_neuropipe.lib.reporting" = ["*.html"]
"qmri_neuropipe.lib.dmri" = ["data/*"]
