# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry install --with docs

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build PDF/EPUB
formats:
  - pdf
  - epub

# Python requirements
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
